name: Validate integration

on:
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  hassfest:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - uses: home-assistant/actions/hassfest@master

  hacs:
    runs-on: ubuntu-26.04
    steps:
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands description topics
